### ISSUE TITLE
Stereo calibration with different resolution cameras?

### ISSUE THREAD

**Issue by antithing** [ftdlyc/libcalib#2]
(editing question as I saw the answer to my first question in a closed issue)

I am looking to stereo calibrate different cameras, with different resolutions. Would this code work in that case? Do I need to adjust any parameters? Does it expect the same resolution, or does it detect it?

Thank you very much for making this code available.

**Comment by ftdlyc** [comment]
@antithing Different resolutions is support by this code. I think you do no need to adjust any parameters.

**Comment by antithing** [comment]
Hi, thanks for getting back to me. I do have it working now with the different cameras, but the T and R results are very different each run. 

Is there anything that I can look at to get a more repeatable result?

Thanks again!
